add labels to dependabot PRs
digitalocean/ansible-collection pull request #20
Opened 2023-07-31 18:20 UTC by artis3n

2023-07-31 18:49 UTC, mamercad requested changes
We need the [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#creating-changelog-fragments) please :sammy-heart:

2023-08-01 12:17 UTC, mamercad commented on changelogs/fragments/18-devcontainer.yaml
> +minor_changes:
Nit: By their docs, each of these items should end in `(https://github.com/digitalocean/ansible-collection/pull/20).` (note the final period as well).

I'll leave that up to you.

2023-08-01 12:17 UTC, mamercad approved these changes
🚀

2023-08-01 13:47 UTC, artis3n commented on changelogs/fragments/18-devcontainer.yaml
> +minor_changes:
Ah, good call out, thank you

2023-08-01 15:48 UTC, mamercad approved these changes
🚢

2023-08-01 16:54 UTC, merged